### ISSUE TITLE
Use method names as RPC name

### ISSUE THREAD

**Issue by kilaka** [RitwikSaikia/jsonrpc#13]
[Enhancement suggestion]

Why register only one interface with only one RPC name each time (executor.addHandler)? **Writing an interface for each RPC is very cumbersome.**
Why not use an interface with several methods and mark some of the methods as RPC methods - using annotation?

Example:

interface Example {
@RPC
void do1();
// not RPC
void do2();
@RPC
void do3();
}

**Comment by RitwikSaikia** [comment]
You can add as many interfaces as you need.

``` java

public interface Addition {
   int add(int x, int y);
}

public interface Multiplication {
   int multiply(int x, int y);
}

public class CalculatorImpl implements Addition, Multiplication {
   ...
}

executor.addHandler("calc", new CalculatorImpl(), Addition.class, 
        Multiplication.class, ...);

executor.addHandler("adder", new CalculatorImpl(), Addition.class);

executor.addHandler("multiplier", new CalculatorImpl(), Multiplication.class);
```

Its your design choice, whether you want to have many interfaces or just one. 

Annotations, can be added. But I want to keep the library simple, enabling more ways of doing the same thing means, more confusion. Let it be like that :)

**Comment by kilaka** [comment]
Ritwik, you're too nice. You could have just said: FTFM :)
