### ISSUE TITLE
Big binary data as a parameter or return value

### ISSUE THREAD

**Issue by kilaka** [RitwikSaikia/jsonrpc#14]
Can this be done using the jsonrpc library?

Example: passing a zip file or a video file.

Perhaps it can be achieved using Input/Output streams? How can I access the io stream?

**Comment by RitwikSaikia** [comment]
jsonrpc is a lightweight protocol, technically javascripts/browsers can't create/process payload of more than 1MB without hitting performance issue. Ideally you should pass on urls to zip/video files to the client, and client should download it from the urls returned.
