### ISSUE TITLE
Android integration

### ISSUE THREAD

**Issue by CarlKabbe** [RitwikSaikia/jsonrpc#15]
How do I use add the client side to Android so that I can have a Android client with a Java server?

**Comment by RitwikSaikia** [comment]
If you are building via Maven, use following tag in ur dependencies in  pom.xml

``` xml
<dependency>
    <groupId>org.json.rpc</groupId>
    <artifactId>jsonrpc</artifactId>
    <version>1.0</version>
    <classifier>client</classifier>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-android</artifactId>
    <version>1.6.1-RC1</version>
</dependency>
```

You will need to add following repository 

``` xml
<repositories>
   <repository>
      <id>ritwik-mvn-repo</id>
      <url>http://ritwik.net/mvn/releases/</url>
   </repository>
</repositories>
```

Other wise include [slf4j-android](http://www.slf4j.org/android/) jar and [jsonrpc-client.jar](http://ritwik.net/mvn/releases/org/json/rpc/jsonrpc/1.0/jsonrpc-1.0-client.jar) to your android project.

To make a call from client 

``` java
// where your servlet is hosted
String url = "http://my-server.com:8080/jsonrpc"; 

HttpJsonRpcClientTransport transport = new HttpJsonRpcClientTransport(new URL(url));

JsonRpcInvoker invoker = new JsonRpcInvoker();
Calculator calc = invoker.get(transport, "calc", Calculator.class);

double result = calc.add(1.2, 7.5);
```

Hope that answers your query.

**Comment by CarlKabbe** [comment]
http://mvn.ritwik.net/releases/org/json/rpc/jsonrpc/1.0/jsonrpc-1.0-client.jar is broken, as in when I click on it google just suggests going to ritwik.net

**Comment by RitwikSaikia** [comment]
Correct link : http://ritwik.net/mvn/releases/org/json/rpc/jsonrpc/1.0/jsonrpc-1.0-client.jar

**Comment by CarlKabbe** [comment]
I followed your examples for client and server and I am trying to test them.
When I do the call in Android I can hit my breakpoint I set in the Java server servlet constructor and then when it goes to the line below it fails
            JsonRpcExecutor executor = new JsonRpcExecutor();
I have the jsonrpc-1.0-server.jar included in my server project

And if I try again I don't even hit a breakpoint I have left in the doPost method for the Java server
