### ISSUE TITLE
Javascript integration

### ISSUE THREAD

**Issue by kilaka** [RitwikSaikia/jsonrpc#9]
This looks like a well thought/implemented library and I'd like to use it in javascript in additional to Java - on the client side of course.

I think that it was not supposed to work with javascript, as it encapsulates the protocol in Java interfaces and Javascript doesn't have interfaces. But still I would like to know if it's possible somehow.

How can I do it? Can you please post an enhancement to your example for javascript as well?

Thanks.

*\* I want to emphasize that this is not a bug. I wanted to add the 'question' label to this issue, but couldn't find a way to do it in github.

**Comment by kilaka** [comment]
Silly me. I missed it:
https://github.com/RitwikSaikia/jsonrpc#call-from-javascript-client

**Comment by RitwikSaikia** [comment]
:), I was about to paste the same reference.
